-- Boshlang'ich sxema: 6-bosqich yakunidagi entity'lar holati.
--
-- Enum ustunlarida (status, role, state) CHECK constraint yo'q. Hibernate uni o'zi
-- qo'yardi, lekin `ddl-auto: validate` CHECK'ni tekshirmaydi: enum'ga yangi qiymat
-- qo'shilib migratsiya esdan chiqsa, dastur bemalol ko'tariladi va faqat runtime'da,
-- shu qiymat yozilganda portlaydi (5-bosqichdagi users_state_check). Qiymatlar
-- to'g'riligini EnumType.STRING kafolatlaydi.

create table users (
    id                    bigint generated by default as identity,
    telegram_id           bigint       not null,
    name                  varchar(255),
    phone                 varchar(255),
    role                  varchar(255),
    state                 varchar(255),
    draft_product_id      bigint,
    draft_receipt_file_id varchar(255),
    created_at            timestamp(6),
    updated_at            timestamp(6),
    constraint users_pkey primary key (id),
    constraint users_telegram_id_key unique (telegram_id)
);

create table product (
    id         bigint generated by default as identity,
    name       varchar(255),
    price      numeric(38, 2),
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint product_pkey primary key (id),
    constraint product_name_key unique (name)
);

create table cart_items (
    id         bigint generated by default as identity,
    user_id    bigint  not null,
    product_id bigint  not null,
    quantity   integer not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint cart_items_pkey primary key (id),
    constraint cart_items_user_product_key unique (user_id, product_id),
    constraint cart_items_user_fk foreign key (user_id) references users (id),
    constraint cart_items_product_fk foreign key (product_id) references product (id)
);

create table orders (
    id                 bigint generated by default as identity,
    user_id            bigint,
    status             varchar(255) not null,
    total_amount_money numeric(38, 2),
    receipt_file_id    varchar(255),
    created_at         timestamp(6),
    updated_at         timestamp(6),
    constraint orders_pkey primary key (id),
    constraint orders_user_fk foreign key (user_id) references users (id)
);

-- product_id nullable: mahsulot o'chirilganda service uni null qiladi, nom va narx
-- esa quyidagi *_at_order ustunlarida muzlatilgan (23-qaror)
create table order_item (
    id                    bigint generated by default as identity,
    order_id              bigint,
    product_id            bigint,
    quantity              integer not null,
    product_name_at_order varchar(255),
    price_at_order        numeric(38, 2),
    created_at            timestamp(6),
    updated_at            timestamp(6),
    constraint order_item_pkey primary key (id),
    constraint order_item_order_fk foreign key (order_id) references orders (id),
    constraint order_item_product_fk foreign key (product_id) references product (id)
);
